### ISSUE TITLE
"/simc" doesn't work

### ISSUE THREAD

**Issue by gdlcf88** [simulationcraft/simc-addon#18]
Cloned from this repo in World of Warcraft\_retail_\Interface\AddOns\Simulationcraft.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/61435043-3017bb80-a96a-11e9-9cbf-1aa13c463ed8.png)

**Comment by seriallos** [comment]
If you grab it straight from the repo, I believe you'll need the dependencies also available (Ace and a bunch of libs).

You can find the list of which libs are used in Simulationcraft.toc

**Comment by gdlcf88** [comment]
```
Message: Interface\AddOns\Simulationcraft\core.lua:3: Cannot find a library instance of "AceAddon-3.0".
Time: Thu Jul 18 14:47:49 2019
Count: 1
Stack: Interface\AddOns\Simulationcraft\core.lua:3: Cannot find a library instance of "AceAddon-3.0".
[C]: in function `error'
...face\AddOns\Simulationcraft\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\Simulationcraft\core.lua:3: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceAddon-3.0"."

```

You are right, thanks.
