### ISSUE TITLE
Sim wwill not open

### ISSUE THREAD

**Issue by Snowmanmc87** [simulationcraft/simc-addon#20]
5x Simulationcraft\core.lua:5: Cannot find a library instance of "LibRealmInfo".
[string "=[C]"]: in function error' [string "@ElvUI\Libraries\Ace3\LibStub\LibStub.lua"]:23: in function LibStub'
[string "@simulationcraft\core.lua"]:5: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibRealmInfo"."

**Comment by seriallos** [comment]
You either need to install the addon via the Twitch client or make sure you have the LibRealmInfo addon installed.
