### ISSUE TITLE
Latest alpha throws errors in BfA

### ISSUE THREAD

**Issue by Molkree** [simulationcraft/simc-addon#21]
Latest alpha v9.0.1-alpha-1 throws errors upon login on Retail.
Getting 4 of this on every login/reload. Only addons enabled are BugGrabber, BugSack and Simulationcraft.
```
96x Couldn't find inherited node: BackdropTemplate
```

**Comment by seriallos** [comment]
The alpha version is intended for Shadowlands. Revert back to the Release version for retail compatibility.

**Comment by Molkree** [comment]
Okay, thanks, I only thought it's supposed to work in 8.3 due to this line https://github.com/simulationcraft/simc-addon/commit/99ae99a0664bbc50d13ea7bf7b0da55ab6aded56#diff-676a4a4e1e11d8a49b083eb4080db4faR742.

**Comment by navv1234** [comment]
It may eventually work with both, however it requires a slight refactoring/rearchitecting of some of the code (that is not related to what you linked to).
