### ISSUE TITLE
Wrong Bonus Id for ilvl 200 Tree-Scaler's Britches

### ISSUE THREAD

**Issue by bagelbits** [simulationcraft/simc-addon#27]
### Describe the bug
`/simc` is giving the "Scales with level" instead of the ilvl 200 for [Tree-Scaler's Britches](https://www.wowhead.com/item=184753/tree-scalers-britches):
```
legs=,id=184753,bonus_id=7240,drop_level=60
```

### Expected behavior
Upon running `/simc`, the legs line should be:
```
legs=,id=184753,bonus_id=1587,drop_level=60
```

### To Reproduce
Buy the ilvl 200 [Tree-Scaler's Britches](https://www.wowhead.com/item=184753/tree-scalers-britches) from either Wild Hunt Quartermaster and equip them. Then run `simc`.

### Additional information
* SimulationCraft Version
9.0.2-15

**Comment by seriallos** [comment]
Looks like a duplicate got posted so closing this one.
