### ISSUE TITLE
Host the addon outside of CurseForge

### ISSUE THREAD

**Issue by JVemmer** [simulationcraft/simc-addon#29]
As CurseForge is locking out everyone except Overwolf's own addon manager (source: [https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912](https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912)), please host this addon elsewhere than CurseForge (at least co-host it elsewhere). Options include:

- Hosting a .zip file of the addon here in the GitHub repository (this allows WowUp to pull it down)
- Hosting it on WowUpHub website
- Hosting it on wago.io (allows monetization to continue, if that is a concern)
- Hosting it on TukUI
- Hosting it on WowInterface

I am personally using WowUp to update addons, and while I very much respect that some addon creators want their work monetized, and believe that they should have the option, I do not support the Overwolf lock-out simply because they want everyone to use their app. If monetization is a priority, I suggest using wago.io as addon hosting, as it allows for monetization of addons, also while using WowUp; which shows they're willing to find solutions, rather than the Overwolf approach of refusing to cooperate.
I don't mind anyone hosting their addons on CurseForge, but please, please, please host it outside of CurseForge as well, for those of us who would like to cut ties with CurseForge, but still use your amazing addon :heart:

**Comment by seriallos** [comment]
Yup, I'll be looking into this sometime in the next week or two.

**Comment by navv1234** [comment]
Judging by some scripts available, it might be easiest to simply package to github releases.

**Comment by seriallos** [comment]
Yeah, BigWigs has a packaging script that looks pretty easy to use (https://github.com/BigWigsMods/packager). I'll be tinkering with it when I can find some time.

**Comment by Ravenwylde** [comment]
Thank you for being accommodating! It is very much appreciated, and you are very much appreciated as well.

**Comment by seriallos** [comment]
SimC addon will now create GitHub releases in addition to releasing to CurseForge:

https://github.com/simulationcraft/simc-addon/releases

You should be able to use that URL in WowUp to track the latest updates to this addon.
