### ISSUE TITLE
Failing to import data from Addon

### ISSUE THREAD

**Issue by rodolphocaires** [simulationcraft/simc-addon#3]
# SimulationCraft encountered an error!
* Category: Simulation setup error
* Error: Unknown option 'artifact' with value '32:0:0:0:0:1102:1:1103:4:1104:4:1105:4:1106:4:1107:4:1108:4:1109:4:1110:4:1111:4:1112:1:1113:1:1114:1:1115:1:1116:1:1117:1:1352:1:1389:1:1597:4:1598:1:1599:1:1600:7:1693:1'

[log.txt](https://github.com/simulationcraft/simc-addon/files/1129487/log.txt)

**Comment by seriallos** [comment]
This looks like an old version of SimulationCraft, not an issue with the WoW addon.
