### ISSUE TITLE
attempt to call global 'GetSpecialization' (a nil value)

### ISSUE THREAD

**Issue by Kilmatar** [simulationcraft/simc-addon#31]
When trying to open simc in LK Classic:

 

Date: 2022-09-30 14:27:32
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Simulationcraft\core.lua line 750:
attempt to call global 'GetSpecialization' (a nil value)
Debug:
[string "=[C]"]: GetSpecialization()
[string "@Simulationcraft\core.lua"]:750: PrintSimcProfile()
[string "@Simulationcraft\core.lua"]:16: OnClick()
[string "@Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144:
...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142
Locals:

AddOns:
Swatter, v3.4.6817 (SwimmingSeadragon)
WowheadLooter, v30400
Ace3, vr1292
AdvancedInterfaceOptions, v1.7.2-2-g3742126
AlreadyKnown, v1.46
Altoholic, v2.5.008
Atlas, vv1.51.06
AtlasBurningCrusade, vv1.51.02
AtlasClassicWoW, vv1.51.02
AtlasDungeonLocs, vv1.51.07
AtlasTransportation, vv1.51.08
AtlasWrathoftheLichKing, vv1.51.02
AtlasLootClassic, vv3.0.3
AtlasLootClassicData, vv3.0.3
AtlasLootClassicDungeonsAndRaids, vv3.0.3
AtlasQuest, v4.13.02
AucAdvanced, v3.4.6831 (SwimmingSeadragon)
AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
AucScanData, v3.4.6804 (SwimmingSeadragon)
AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
AucStatSimple, v3.4.6807 (SwimmingSeadragon)
AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
BeanCounter, v3.4.6811 (SwimmingSeadragon)
ChatBarClassic, v3.22a-WotLK
ClassicCastbars, vv1.5.1
ClassicCastbarsOptions, vv1.5.1
ClassicProfessionFilter, v1.0.8-beta
DataStore, v2022.06.05
DataStoreAgenda, v2.5.008
DataStoreAuctions, v2.5.008
DataStoreCharacters, v2022.06.05
DataStoreContainers, v2.5.008
DataStoreCrafts, v2.5.008
DataStoreInventory, v2.5.008
DataStoreMails, v2022.06.05
DataStoreQuests, v2.5.008
DataStoreReputations, v2.5.008
DataStoreSpells, v2022.06.05
DataStoreTalents, v2.5.008
DBMCore, vb953898
DBMStatusBarTimers, vb953898
DBMVPVEM, v1b93adf
Decursive, v2.7.8.9
Dominos, v9.3.5
DominosCast, v
DominosEncounter, v
DominosProgress, v
DominosRoll, v
GatherMate2, v1.46.3-classic
HandyNotes, vv1.6.8
HandyNotesDungeonLocationsClassic, v1.06a-classic
HandyNotesHigherLearning, v1.09
HandyNotesNPCsClassic, v1.30a
HandyNotesTravelGuide, vv1.2
HealBot, v3.4.0.0.b8
HealBotData, v2.5.4.20
HealBotOptions, v3.4.0.0
HealBotPluginCombatProt, v3.4.0.0
HealBotTips, v3.4.0.0
HealerProtection, v1.0.4
Informant, v3.4.6814 (SwimmingSeadragon)
LeatrixMaps, v3.0.11
LeatrixPlus, v3.0.13
MikScrollingBattleText, v5.7.153
ModernTargetFrame, v1.11
Molinari, v90207.84-Release
Pawn, v2.7.1
PLG, v2.5
Postal, vv3.8.2
Prat30, v3.9.2
Prat30Libraries, v
ProfessionAssistance, v4.0.3
Questie, v7.2.4
QuestXP, v0.8.1
SexyMap, vv9.2.11
Simulationcraft, v10.0.0-alpha-05
SmexyMats, vClassic + TBC
SpellActivationOverlay, v0.6.4
Stubby, v3.4.6816 (SwimmingSeadragon)
TellMeWhen, v9.2.6
TomTom, vv3.1.4
VendorPrice, v1.6.0
WhatsTraining, v4.0.3
WIM, v3.9.6-5-g9a39dc0
ZPerl, v6.3.4
ZPerlArcaneBar, v
ZPerlParty, v
ZPerlPlayer, v
ZPerlPlayerBuffs, v
ZPerlPlayerPet, v
ZPerlRaidFrames, v
ZPerlTarget, v
BlizRuntimeLib_ruRU v3.4.0.30400 <none>
(ck=aab)

**Comment by seriallos** [comment]
The SimC addon only supports the current retail expansion. There are currently no plans for Classic support.
