### ISSUE TITLE
Items in bank assigned to wrong slot

### ISSUE THREAD

**Issue by zzjkdutr** [simulationcraft/simc-addon#36]
Items in the bank (while the bank window is open) are being assigned to the wrong slot.

eg:
```
# Swoglet Stompers (372)
# neck=,id=193770,bonus_id=7977/40/8814/1594/8767
#
# Ohn'ahran Falconer's Grips (366)
# neck=,id=191999,bonus_id=6652/1468/5865/8766
#
# Gnollish Chewtoy Launcher (369)
# neck=,id=200266,bonus_id=6652/1472/5864/8766
#
# Ohn'ahran Falconer's Coif (366)
# neck=,id=192000,bonus_id=6652/7937/1468/5865/8766
```
Stompers are feet. grips are hands, launcher is a weapon, coif is head, ...

**Comment by seriallos** [comment]
This is a bug in WoW itself, not specific to the addon. The built-in Equipment Manager in the character panel is broken in a similar way when the bank is open.

As far as I know, Blizzard is aware of this problem so hopefully they will fix it sometime soon.
