### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by igorrebolj** [simulationcraft/simc-addon#37]
writing /simc gives me this:
Latest version, started today, tried to update and reinstall.
It is connected to some other addon since error goes away if i disable all addons besides simc.

Message: Interface/AddOns/Simulationcraft/core.lua:462: invalid value (nil) at index 1 in table for 'concat'
Time: Sat Mar 11 16:43:43 2023
Count: 1
Stack: Interface/AddOns/Simulationcraft/core.lua:462: invalid value (nil) at index 1 in table for 'concat'
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `concat'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:462: in function <Interface/AddOns/Simulationcraft/core.lua:422>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:532: in function `GetItemStrings'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:893: in function `PrintSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:149: in function `?'
[string "@Interface/AddOns/Ace3/AceConsole-3.0/AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5229: in function <Interface/FrameXML/ChatFrame.lua:5175>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4893: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4929: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:

**Comment by seriallos** [comment]
SimC addon hasn't been updated recently so it must be some there addon that is interfering. Can you figure out which addon is causing the conflict? If I know what other addon is causing the problem, I can figure out what's going on and potentially fix it in SimC and/or contact the other addon's author to see if they can fix the issue.

**Comment by igorrebolj** [comment]
I did install today skada for short time since i was testing something, but i removed it already.
Will go thru active addons to see what is the problem and let you know.

**Comment by seriallos** [comment]
Believe this should now be fixed based on conversation and testing in the Raidbots Discord!
