### ISSUE TITLE
Retribution Paladin

### ISSUE THREAD

**Issue by dasbumsding** [simulationcraft/simc-addon#39]
Describe the bug
When I type "/simc" in chat, I can't click enter. I can't click on the minimap icon either. I'm not getting any input. Other Retri players that I know don't have the problem. If I switch to Prot or Heal, simulationcraft works. Simc also works with other classes. Only Retri Pala does not work.

Expected behavior
If I type "/simc" in the chat, I can click enter. Then a new window appears where I can copy the content. But I can't even click enter.

To Reproduce
see up.

Additional information
I'm up-to-date. I testing since 3 Version from simulationcraft (now 10.0.7-3)

**Comment by seriallos** [comment]
The issue is that pre-10.0.7 Retribution talent builds are broken and you need to recreate or delete any old builds.

The latest version of the addon prints an error that in your main chat window that includes the name of the talent build that is causing issues.
