### ISSUE TITLE
Elvui (13.32) seems to block SimC (10.1.0-04) from exporting Great Vault items

### ISSUE THREAD

**Issue by robw001** [simulationcraft/simc-addon#43]
When using ElvUI 13.32, opening the Great Vault and running /simc, the addon generates a warning message "Warning: SimC was unable to retrieve an item name from your Great Vault, try again". GV items are not present in the simc output.

When I then disable ElvUI, the warning message is not shown and SimC correctly exports GV items.

Apparently, this has been the case for a while, since I never had GV items in my SimC output and I have been using ElvUI for a long time.

**Comment by robw001** [comment]
I don't think so. I did get the Warning messages after running /simc several times in a row. It seems however that the problem has fixed itself, Simc now properly picks up Vault items with ElvUI both on and off. This issue can be closed.

**Comment by seriallos** [comment]
That's super weird. I know there are some cases where some addons (usually related to transmog) can do a ton of item lookups all at once which can cause throttling for other addons. Definitely let me know if it shows back up again!
