### ISSUE TITLE
Empty gear slots

### ISSUE THREAD

**Issue by ChloeMarie** [simulationcraft/simc-addon#44]
When I try uploading it to sim my main, it says it's loading with empty gear slots.

![emptyslots](https://github.com/simulationcraft/simc-addon/assets/11381006/6a8bf41a-6dd9-4c73-8dc1-0569a098aa88)

**Comment by seriallos** [comment]
Please post your /simc input and/or your region/realm/name.

Also, do you have empty gear slots?

**Comment by ChloeMarie** [comment]
No empty gear slots.

# Tyrenni - Demonology - 2023-07-11 17:08 - US/Emerald Dream
# SimC Addon 10.1.0-10
# WoW 10.1.5.50401, TOC 100105
# Requires SimulationCraft 1000-01 or newer

warlock="Tyrenni"
level=70
race=void_elf
region=us
server=emerald_dream
role=spell
professions=tailoring=100/enchanting=100
spec=demonology

talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKhkIAkkkQSKaJ5AJEAAAAAAkA

# Saved Loadout: Immutable Hatred Single Target
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRI5AIKRScgQSKaJ5AJEAAAAAAkA
# Saved Loadout: Immutable Hatred Cleave / AOE
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ
# Saved Loadout: GrandWarlocksDesign / Guilloti
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAaRQOAJaRScgIJRaJRCBAAAAAAJ
# Saved Loadout: Underrot
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ
# Saved Loadout: Neltharion's Lair
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ

# Grimhorns of the Sinister Savant (441)
head=,id=202533,gem_id=192985,bonus_id=6652/9229/9334/1498/8767/9413
# Amice of the Sinister Savant (441)
shoulder=,id=202531,bonus_id=6652/9227/9380/1498/8767
# Shawl of the Sinister Savant (437)
back=,id=202528,enchant_id=6592,bonus_id=40/9409/8094/9333/1494/8767
# Cursed Robes of the Sinister Savant (437)
chest=,id=202536,enchant_id=6625,bonus_id=6652/9231/9409/9333/1488/8767
# Tailored Officer's Shirt (1)
shirt=,id=89194
tabard=,id=69210
# Clasps of the Diligent Steward (437)
wrist=,id=204393,bonus_id=6652/9415/9226/9220/9409/9333/1488/8767
# Phoenix-Plume Gloves (437)
hands=,id=202578,bonus_id=9409/6652/9226/9218/9333/1494/8767
# Sash of Abandoned Hope (437)
waist=,id=202589,gem_id=192967,bonus_id=9409/6652/9226/9219/9333/1494/8767/9413
# Leggings of the Sinister Savant (441)
legs=,id=202532,enchant_id=6541,bonus_id=6652/9228/9334/1498/8767
# Vibrant Wildercloth Slippers  (437)
feet=,id=193519,enchant_id=6607,bonus_id=8836/8840/8902/9405/9373/8793/8174/9366,crafted_stats=49/36,crafting_quality=5
# Onyx Impostor's Birthright (437)
finger1=,id=204398,enchant_id=6562,bonus_id=6652/9415/9409/9333/1485/8767
# Skyshard Ring (437)
finger2=,id=206184,enchant_id=6562,bonus_id=41/9414/9144/9329/1659/8767
# Irideus Fragment (437)
trinket1=,id=193743,bonus_id=42/9144/9329/1659/8767
# Spoils of Neltharus (437)
trinket2=,id=193773,bonus_id=40/9144/9329/1659/8767
# Erethos, the Empty Promise (437)
main_hand=,id=202565,enchant_id=6643,bonus_id=7979/9329/1485/8767

### Gear from Bags
#
# head=,id=193543,bonus_id=8843/8842/8807,crafting_quality=5
#
# head=,id=188734,bonus_id=7966,drop_level=70
#
# Suffused Cowl (411)
# head=,id=204786,bonus_id=9316/6652/9415/9223/9221/1533/8767
#
# head=,id=188734,bonus_id=7966,drop_level=70
#
# Hood of Arcane Mystery (385)
# head=,id=109970,bonus_id=6652/8812/9407/7756/9492,drop_level=70
#
# Suffused Choker (389)
# neck=,id=204732,bonus_id=9302/6652/9415/8784/1511/8766
#
# Timeworn Chain Spaulders (180)
# shoulder=,id=188729,bonus_id=7966,drop_level=70
#
# shoulder=,id=188714,bonus_id=7966,drop_level=70
#
# shoulder=,id=109932,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Mystic's Scalding Frame (415)
# shoulder=,id=202580,bonus_id=9321/7979/6652/9222/9218/1472/8767
#
# Cloak of Coordination (29)
# back=,id=65360
#
# Suffused Cuffs (405)
# wrist=,id=204783,bonus_id=9314/6652/9415/9223/9220/1527/8767
#
# wrist=,id=188720,bonus_id=7966,drop_level=70
#
# Felflame Grips (385)
# hands=,id=109861,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Timeworn Chain Gauntlets (180)
# hands=,id=188733,bonus_id=7966,drop_level=70
#
# Felflame Sandals (385)
# feet=,id=109797,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Sandals of Arcane Mystery (385)
# feet=,id=109784,bonus_id=6652/9407/7756/9492,drop_level=70
#
# main_hand=,id=128942,bonus_id=747
#
# main_hand=,id=204752,bonus_id=9304/6652/1517/8766
#
# Nokhud Whittling Knife (193)
# main_hand=,id=201934,bonus_id=7967,drop_level=70
#
# Skull of the Man'ari (10)
# off_hand=,id=128943,bonus_id=748

### Weekly Reward Choices
#
### End of Weekly Reward Choices

### Additional Character Info
#
# upgrade_currencies=c:1792:1985/c:2122:18/c:2245:862/i:204195:36/i:204440:2/i:204673:1/i:204193:24/i:204682:1/i:198058:1/i:204196:11
#
# slot_high_watermarks=0:441:441/1:433:433/2:441:441/3:437:437/4:437:437/5:441:441/6:437:437/7:437:437/8:437:437/9:437:437/10:437:437/11:437:437/12:437:437/13:437:437/14:47:100/15:45:100/16:424:424

# Checksum: 7cc3136e

**Comment by ChloeMarie** [comment]
No empty gear slots

US / Emerald Dream / Tyrenni

# Tyrenni - Demonology - 2023-07-11 17:08 - US/Emerald Dream
# SimC Addon 10.1.0-10
# WoW 10.1.5.50401, TOC 100105
# Requires SimulationCraft 1000-01 or newer

warlock="Tyrenni"
level=70
race=void_elf
region=us
server=emerald_dream
role=spell
professions=tailoring=100/enchanting=100
spec=demonology

talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKhkIAkkkQSKaJ5AJEAAAAAAkA

# Saved Loadout: Immutable Hatred Single Target
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRI5AIKRScgQSKaJ5AJEAAAAAAkA
# Saved Loadout: Immutable Hatred Cleave / AOE
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ
# Saved Loadout: GrandWarlocksDesign / Guilloti
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAaRQOAJaRScgIJRaJRCBAAAAAAJ
# Saved Loadout: Underrot
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ
# Saved Loadout: Neltharion's Lair
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkiCRaJJhUCAAAAAKRQOAJKRScgIJRaJRCBAAAAAAJ

# Grimhorns of the Sinister Savant (441)
head=,id=202533,gem_id=192985,bonus_id=6652/9229/9334/1498/8767/9413
# Amice of the Sinister Savant (441)
shoulder=,id=202531,bonus_id=6652/9227/9380/1498/8767
# Shawl of the Sinister Savant (437)
back=,id=202528,enchant_id=6592,bonus_id=40/9409/8094/9333/1494/8767
# Cursed Robes of the Sinister Savant (437)
chest=,id=202536,enchant_id=6625,bonus_id=6652/9231/9409/9333/1488/8767
# Tailored Officer's Shirt (1)
shirt=,id=89194
tabard=,id=69210
# Clasps of the Diligent Steward (437)
wrist=,id=204393,bonus_id=6652/9415/9226/9220/9409/9333/1488/8767
# Phoenix-Plume Gloves (437)
hands=,id=202578,bonus_id=9409/6652/9226/9218/9333/1494/8767
# Sash of Abandoned Hope (437)
waist=,id=202589,gem_id=192967,bonus_id=9409/6652/9226/9219/9333/1494/8767/9413
# Leggings of the Sinister Savant (441)
legs=,id=202532,enchant_id=6541,bonus_id=6652/9228/9334/1498/8767
# Vibrant Wildercloth Slippers  (437)
feet=,id=193519,enchant_id=6607,bonus_id=8836/8840/8902/9405/9373/8793/8174/9366,crafted_stats=49/36,crafting_quality=5
# Onyx Impostor's Birthright (437)
finger1=,id=204398,enchant_id=6562,bonus_id=6652/9415/9409/9333/1485/8767
# Skyshard Ring (437)
finger2=,id=206184,enchant_id=6562,bonus_id=41/9414/9144/9329/1659/8767
# Irideus Fragment (437)
trinket1=,id=193743,bonus_id=42/9144/9329/1659/8767
# Spoils of Neltharus (437)
trinket2=,id=193773,bonus_id=40/9144/9329/1659/8767
# Erethos, the Empty Promise (437)
main_hand=,id=202565,enchant_id=6643,bonus_id=7979/9329/1485/8767

### Gear from Bags
#
# head=,id=193543,bonus_id=8843/8842/8807,crafting_quality=5
#
# head=,id=188734,bonus_id=7966,drop_level=70
#
# Suffused Cowl (411)
# head=,id=204786,bonus_id=9316/6652/9415/9223/9221/1533/8767
#
# head=,id=188734,bonus_id=7966,drop_level=70
#
# Hood of Arcane Mystery (385)
# head=,id=109970,bonus_id=6652/8812/9407/7756/9492,drop_level=70
#
# Suffused Choker (389)
# neck=,id=204732,bonus_id=9302/6652/9415/8784/1511/8766
#
# Timeworn Chain Spaulders (180)
# shoulder=,id=188729,bonus_id=7966,drop_level=70
#
# shoulder=,id=188714,bonus_id=7966,drop_level=70
#
# shoulder=,id=109932,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Mystic's Scalding Frame (415)
# shoulder=,id=202580,bonus_id=9321/7979/6652/9222/9218/1472/8767
#
# Cloak of Coordination (29)
# back=,id=65360
#
# Suffused Cuffs (405)
# wrist=,id=204783,bonus_id=9314/6652/9415/9223/9220/1527/8767
#
# wrist=,id=188720,bonus_id=7966,drop_level=70
#
# Felflame Grips (385)
# hands=,id=109861,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Timeworn Chain Gauntlets (180)
# hands=,id=188733,bonus_id=7966,drop_level=70
#
# Felflame Sandals (385)
# feet=,id=109797,bonus_id=6652/9407/7756/9492,drop_level=70
#
# Sandals of Arcane Mystery (385)
# feet=,id=109784,bonus_id=6652/9407/7756/9492,drop_level=70
#
# main_hand=,id=128942,bonus_id=747
#
# main_hand=,id=204752,bonus_id=9304/6652/1517/8766
#
# Nokhud Whittling Knife (193)
# main_hand=,id=201934,bonus_id=7967,drop_level=70
#
# Skull of the Man'ari (10)
# off_hand=,id=128943,bonus_id=748

### Weekly Reward Choices
#
### End of Weekly Reward Choices

### Additional Character Info
#
# upgrade_currencies=c:1792:1985/c:2122:18/c:2245:862/i:204195:36/i:204440:2/i:204673:1/i:204193:24/i:204682:1/i:198058:1/i:204196:11
#
# slot_high_watermarks=0:441:441/1:433:433/2:441:441/3:437:437/4:437:437/5:441:441/6:437:437/7:437:437/8:437:437/9:437:437/10:437:437/11:437:437/12:437:437/13:437:437/14:47:100/15:45:100/16:424:424

# Checksum: 7cc3136e

**Comment by seriallos** [comment]
That /simc output does not have a neck equipped. Try running /simc again and see if your neck shows up.

It looks like you might be running some addons that are doing a lot of item lookups / database work which could be interfering with the SimC addon. I haven't seen it fail in this way before (completely missing an item). If it keeps happening, can you provide a list of other addons that you are running?
