### ISSUE TITLE
/simc No response

### ISSUE THREAD

**Issue by PKAV69** [simulationcraft/simc-addon#49]
Is it not working on the recently rebooted Chinese WLK Lich King, version 3.4.3?

I'm pretty sure it's started, but typing /simc doesn't do anything

**Comment by seriallos** [comment]
The SimulationCraft addon only works for retail, not for Classic.

**Comment by PKAV69** [comment]
> The SimulationCraft addon only works for retail, not for Classic.SimulationCraft 插件仅适用于零售，不适用于 Classic。

ok , thanks
