### ISSUE TITLE
LUA ERROR

### ISSUE THREAD

**Issue by knightdea** [simulationcraft/simc-addon#52]
After installing the addon, reinstalling it, rebooting PC, reloading game, this error pops up every time I execute "/simc" :

Message: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly
Time: Thu Aug 29 11:37:15 2024
Count: 1
Stack: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:367: in function <Interface/AddOns/Simulationcraft/core.lua:337>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:393: in function <Interface/AddOns/Simulationcraft/core.lua:379>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:913: in function `GetSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:1055: in function `PrintSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:168: in function `?'
[string "@Interface/AddOns/BetterBags/libs/AceConsole-3.0/AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals: (*temporary) = "Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly"

**Comment by knightdea** [comment]
After disabling all addons but Simulationcraft, I get this error instead:

Message: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly
Time: Thu Aug 29 11:37:15 2024
Count: 1
Stack: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:367: in function <Interface/AddOns/Simulationcraft/core.lua:337>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:393: in function <Interface/AddOns/Simulationcraft/core.lua:379>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:913: in function `GetSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:1055: in function `PrintSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:168: in function `?'
[string "@Interface/AddOns/BetterBags/libs/AceConsole-3.0/AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals: (*temporary) = "Talent loadout 'Single' is corrupt/incomplete. It needs to be recreated or deleted for /simc to function properly"

**Comment by seriallos** [comment]
You have a talent loadout that is corrupted/old and doesn't work with the SimC addon. You need to update or delete the "Single" talent load out in order for the addon to work.

If you see that message again, check the text to see what talent load out is having issues.
