### ISSUE TITLE
Lua error 11.0.2-02

### ISSUE THREAD

**Issue by Gunner-web** [simulationcraft/simc-addon#53]
I'm seeing the below LUA error in the latest version.  Any help?

Message: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'current' is corrupt/incomplete. Find that talent loadout in your talents UI and delete or update it. It may be on a different spec.
Time: Sun Oct  6 10:39:09 2024
Count: 3
Stack: Interface/AddOns/Simulationcraft/core.lua:367: Talent loadout 'current' is corrupt/incomplete. Find that talent loadout in your talents UI and delete or update it. It may be on a different spec.
[string "@Interface/AddOns/Simulationcraft/core.lua"]:367: in function <Interface/AddOns/Simulationcraft/core.lua:337>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:393: in function <Interface/AddOns/Simulationcraft/core.lua:379>
[string "@Interface/AddOns/Simulationcraft/core.lua"]:913: in function `GetSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:1055: in function `PrintSimcProfile'
[string "@Interface/AddOns/Simulationcraft/core.lua"]:19: in function `OnClick'
[string "@Interface/AddOns/Bartender4/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:179: in function <...dOns/Bartender4/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

Locals: exportStream = <table> {
 dataEntries = <table> {
 }
}
configID = 18649626
treeID = 658
treeNodes = <table> {
 1 = 62084
 2 = 62085
 3 = 62086
 4 = 62087
 5 = 62088
 6 = 62089
 7 = 62091
 8 = 62092
 9 = 62093
 10 = 62094
 11 = 62095
 12 = 62096
 13 = 62097
 14 = 62098
 15 = 62099
 16 = 62100
 17 = 62101
 18 = 62102
 19 = 62103
 20 = 62104
 21 = 62105
 22 = 62106
 23 = 62107
 24 = 62108
 25 = 62110
 26 = 62111
 27 = 62112
 28 = 62113
 29 = 62114
 30 = 62115
 31 = 62116
 32 = 62117
 33 = 62118
 34 = 62119
 35 = 62120
 36 = 62121
 37 = 62122
 38 = 62123
 39 = 62124
 40 = 62125
 41 = 62127
 42 = 62128
 43 = 62129
 44 = 62150
 45 = 62151
 46 = 62152
 47 = 62153
 48 = 62154
 49 = 62155
 50 = 62156
 51 = 62157
 52 = 62158
 53 = 62159
 54 = 62160
 55 = 62161
 56 = 62162
 57 = 62163
 58 = 62164
 59 = 62165
 60 = 62166
 61 = 62167
 62 = 62168
 63 = 62169
 64 = 62170
 65 = 62171
 66 = 62172
 67 = 62173
 68 = 62174
 69 = 62176
 70 = 62177
 71 = 62178
 72 = 62179
 73 = 62180
 74 = 62181
 75 = 62182
 76 = 62183
 77 = 62184
 78 = 62185
 79 = 81467
 80 = 81468
 81 = 93524
 82 = 94632
 83 = 94633
 84 = 94634
 85 = 94635
 86 = 94636
 87 = 94637
 88 = 94638
 89 = 94639
 90 = 94640
 91 = 94641
 92 = 94642
 93 = 94643
 94 = 94644
 95 = 94645
 96 = 94646
 97 = 94647
 98 = 94648
 99 = 94649
 100 = 94650
 101 = 94651
 102 = 94652
 103 = 94653
 104 = 94654
 105 = 94655
 106 = 94656
 107 = 94657
 108 = 94658
 109 = 94659
 110 = 94660
 111 = 94661
 112 = 94662
 113 = 94663
 114 = 94664
 115 = 99828
 116 = 99829
 117 = 99830
 118 = 100987
 119 = 100988
 120 = 100989
 121 = 100991
 122 = 100992
 123 = 100993
 124 = 100994
 125 = 100995
 126 = 100996
 127 = 100997
 128 = 100998
 129 = 100999
 130 = 101000
 131 = 101001
 132 = 101002
 133 = 101003
 134 = 101004
 135 = 101006
 136 = 101007
 137 = 101008
 138 = 101009
 139 = 101011
 140 = 101012
 141 = 101013
 142 = 101014
 143 = 101015
 144 = 101016
 145 = 101017
 146 = 101019
 147 = 101020
 148 = 101021
 149 = 101022
 150 = 101023
 151 = 101024
 152 = 101025
 153 = 101027
 154 = 101029
 155 = 101302
 156 = 101883
 157 = 101942
 158 = 101943
 159 = 101945
 160 = 102010
 161 = 102011
 162 = 102012
 163 = 102013
 164 = 102014
 165 = 102435
 166 = 102436
 167 = 102437
 168 = 102438
 169 = 102439
 170 = 102440
 171 = 102441
 172 = 102443
 173 = 102444
 174 = 102445
 175 = 102446
 176 = 102447
 177 = 102448
 178 = 102449
 179 = 102450
 180 = 102451
 181 = 102452
 182 = 102453
 183 = 102454
 184 = 102455
 185 = 102456
 186 = 102457
 187 = 102458
 188 = 102459
 189 = 102460
 190 = 102461
 191 = 102462
 192 = 102463
 193 = 102465
 194 = 102466
 195 = 102467
 196 = 102468
 197 = 102469
 198 = 102470
 199 = 102471
 200 = 102472
 201 = 102473
 202 = 102474
 203 = 102475
 204 = 102476
 205 = 102477
 206 = 102480
 207 = 103771
}
(for state) = <table> {
 1 = 62084
 2 = 62085
 3 = 62086
 4 = 62087
 5 = 62088
 6 = 62089
 7 = 62091
 8 = 6

**Comment by seriallos** [comment]
You have a talent loadout on your character that is broken because of some Blizzard update. You need to find that talent loadout (hit "N" to open your talent UI and check the dropdown in the bottom left corner) and delete it or rebuild it.
