### ISSUE TITLE
[Feature Request] Parse item links passed to the simc commad

### ISSUE THREAD

**Issue by xeropresence** [simulationcraft/simc-addon#8]
It would be awesome if we could pass a item link to the simc command

/simc ITEMLINK 

and have it output the string for the item, either into a box that could be copied from or to the chatbox. Would make determining if items that have dropped and titanforged were upgrades or not.

**Comment by seriallos** [comment]
Coming soon based on @geheur's work in #15 - it will add the item links into a comment to the output, much like gear from bags is handled.
